### ISSUE TITLE
 Problem getting your driving license

### ISSUE THREAD

**Issue by XianPT** [esx-framework/esx_dmvschool#42]
Basically, I take the test, and it appears that I passed the test.
When I go to take the driving test, this option does not appear again to take the code exam.

**Comment by Gellipapa** [comment]
@XianPT Hi! Thank you for reporting this issue. Did you get any error message on server or client side when opening the driving test?

**Comment by XianPT** [comment]
@Gellipapa No.

**Comment by Gellipapa** [comment]
@XianPT Hi! 
![image](https://github.com/esx-framework/esx_dmvschool/assets/22717950/6bffad5a-742c-471d-b249-1772e11683ef)

I did the test twice and both times it fetched the menu. I took a picture of this for you. 

I suggest you update your database table and the esx_dmvschool script itself to the latest version.
